<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>disable</ImplicitUsings>

        <PackageId>NoMewing.FluentIcons</PackageId>
        <Title>NoMewing.FluentIcons</Title>
        <Description>Provides strongly typed access to Segoe Fluent Icons.</Description>
        <PackageTags>icons;fluent;segoe;unicode;glyph</PackageTags>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageProjectUrl>https://github.com/sh0ckj0ckey/MewGet/NoMewing.FluentIcons</PackageProjectUrl>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\..\README.md" Pack="true" PackagePath="\" />
    </ItemGroup>

    <ItemGroup>
        <AdditionalFiles Include="..\..\data\IconsData.json" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\NoMewing.FluentIcons.Generator\NoMewing.FluentIcons.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
    </ItemGroup>

</Project>
